### ISSUE TITLE
Coudn't use backslashes( \\ ) in path for files

### ISSUE THREAD

**Issue by Arkweid** [vxcontrol/soldr-modules#10]
Module coudn't use backslashes( \\\ ) in path for files because of validation. It will cause a problem to read a file on network disk.

**Definition of Done**:
- UI validation allow use backslashes( \\\ )
- Module could read a file on network disk

**Comment by souryogurt** [comment]
I'll take it! It seems there is no escaping for regexp validation pattern.

**Comment by souryogurt** [comment]
I also tested that the file_reader can read updates from network shares. e.g., `\\WIN\Users\Public\test.txt`, because I wasn't sure how the backing custom library works under the hood. Reading network shares works fine.
So the problem was only in UI regexp validation.
