### ISSUE TITLE
Add absolute path

### ISSUE THREAD

**Issue by Arkweid** [vxcontrol/soldr-modules#11]
We cannot specify absolute paths, so we can't read from diffrent disks.

**Definition of Done**:
- Add ability to specify absolute path
- Module could read files from diferent disks (windows, network disks)

**Comment by souryogurt** [comment]
I'll take it! It is related to #10. The module can already read files using absolute paths, so the problem is that users can't physically specify such paths because of an incorrect regexp pattern used in UI for validation.
