### ISSUE TITLE
Could't upload file with the Cyrillic name

### ISSUE THREAD

**Issue by Arkweid** [vxcontrol/soldr-modules#18]
**Step to reproduce**:
- send a Cyrillic file in the path or name via http

**Environment**:
On Windows

**Actual result**:
Error when submitting and via vxapi and when triggering an event with a dispatch action assigned

![file_uploader_cyrrilic](https://user-images.githubusercontent.com/10600777/206994272-43ea7230-a63b-4608-8af3-aefef675275b.png)

**Expected result**:
File sended

**Comment by BurovAV** [comment]
Can contribute, pls assign to me

**Comment by asdek** [comment]
@Arkweid @BurovAV PR was merged to the master
