### ISSUE TITLE
Add rewind feature

### ISSUE THREAD

**Issue by Arkweid** [vxcontrol/soldr-modules#9]
**Description**: Sometimes we need to start read file from beginning.

**Definition of Done**:
- Module could start read file from beginning
- Add "Read from beginning" button in module UI

**Comment by souryogurt** [comment]
I'll take it! It seems the current position for each file is stored in the `store` folder created by the module. I should reset it on the agent's side and restart the watcher thread when the user clicks the "Read from Start" button.
I'll add a new button.
